### ISSUE TITLE
Named key object

### ISSUE THREAD

**Issue by knownasilya** [CrowdStrike/ember-resource-tasks#8]
Why is there an extra object under the `named` key? Seems like extra boilerplate. Is there a use case I'm not seeing?

**Comment by NullVoxPopuli** [comment]
it is boilerplate! All args represented in glimmer/ember are of the shape `{ positional: [...}, named: { ... } }`, and we need libraries to abstract that, like `@glimmer/component`, or `ember-resources` :)

This library will either migrate to ember-resources, or be deprecated in favor of similar utilities provided by ember-resources.
